name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure (Release)
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: cmake --build build -j
      - name: Run unit tests
        run: |
          ./build/test_LruOnly
          ./build/test_LfuCache
          ./build/test_ArcCache
          ./build/test_ArcNew

  sanitizer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure (ASan+UBSan)
        run: |
          cmake -B build-sani -DCMAKE_BUILD_TYPE=Debug \
            -DCMAKE_CXX_FLAGS_DEBUG="-fsanitize=address,undefined -fno-omit-frame-pointer -O1 -g"
      - name: Build
        run: cmake --build build-sani -j
      - name: Run tests with sanitizers
        env:
          ASAN_OPTIONS: halt_on_error=1
        run: |
          ./build-sani/test_LruOnly
          ./build-sani/test_LfuCache
          ./build-sani/test_ArcCache
          ./build-sani/test_ArcNew
